id: A00702FFB
title: Maṇḍala Offering from the Tradition of Jatsön Nyingpo
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:00:26.510822
  last_modified_at: 2022-03-01 00:00:26.510830
