id: A00702FFB
title: Prayer to Rigdzin Jatsön Nyingpo
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:00:26.512920
  last_modified_at: 2022-03-01 00:00:26.512924
